### ISSUE TITLE
Octolapse not doing anything

### ISSUE THREAD

**Issue by GeekDad63** [FormerLurker/Octolapse#247] opened 2018-09-23 23:22 UTC
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: 0.3.1

#### Version of OctoPrint

OctoPrint Version: Version 1.3.9

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES_and_NO Was on but no longer

#### What were you doing when the problem occurred

1. Just printing stuff
2. STEP_TWO_GOES_HERE
3. STEP_...

#### What should have happened?
Should have taken a timelapse

#### What happened instead?
Just printed without any timelapse.

#### Operating System running OctoPrint and Octolapse

OS Name: Octopi
Os Version: 0.13.0

#### Printer model & used firmware incl. version

Printer Model: Monoprice Maker Select V2
Printer Firmware Version: Repetier v??

#### Browser and version of browser, operating system running browser

Browser: 69.0.3497.92
Browser OS: Chrome on Mac osx 10.13.6

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.  I'm currently saving for some additional test cameras in preparation for develiping multi-camera support.

**Comment by GeekDad63** [comment] 2018-09-24 20:46
Where would I find this mysterious plugin_octolapse.log file?

**Comment by FormerLurker** [comment] 2018-09-24 20:50
Sure!  Only download after running a short print in full diagnostic mode though.  You can find it in octoprint settings (wrench)->logs.

Also, did you recently upgrade to Octoprint 1.3.9?  There are some known issues with that version and octolapse 0.3.1.  if you are willing to try a pre-release version of Octolapse, that will likely solve your issue.  Let me know.

**Comment by GeekDad63** [comment] 2018-09-26 18:07
Running the cube test right now but how to I install a previous version of Octolapse?

**Comment by FormerLurker** [comment] 2018-09-26 18:14
You can install a newer version (0.3.4.rc1.dev3) of Octolapse via the plugin manager using this URL:  https://github.com/FormerLurker/Octolapse/archive/v0.3.4rc1.dev3.zip

Click 'Get More' then paste that URL into the '... from URL' text box and click install.  You may want to watch [this](https://www.youtube.com/watch?v=sDyg9lMqMG8&t=18s) video, which explains how to configure your printer profile in the new version (it's a bit different, but pretty easy IMHO).

Maybe give that a go after you print the test cube?

**Comment by GeekDad63** [comment] 2018-09-26 21:10
Can you explain about the slicer settings? Should Octolapse match my slicer (simplify3d) or should my slicer match Octolapse?

**Comment by GeekDad63** [comment] 2018-09-26 21:14
Never mind I got it from the video. OOPS

**Comment by GeekDad63** [comment] 2018-09-26 21:38
Here is a better question. I am getting error messages I can’t seem to resolve as it is asking me to adjust speeds in Slic3r PE which I am not using. Here is a screenshot. Also on an aesthetic level I don’t know what code you use for the windows but is it possible to move all the text in from the left of the screen?

**Comment by FormerLurker** [comment] 2018-09-26 22:00
Can you try reposting that screenshot?

**Comment by GeekDad63** [comment] 2018-09-26 22:07
<img width="700" alt="screenshot 2018-09-26 16 33 26" src="https://user-images.githubusercontent.com/4649074/46111990-94387b80-c1ae-11e8-8967-99367e6f91c0.png">

**Comment by FormerLurker** [comment] 2018-09-26 22:08
Try selecting slic3r pe from the slicer type drop down box (it's set for simplify 3d now).

**Comment by GeekDad63** [comment] 2018-09-26 22:30
My slicer is Simplify3D. Shouldn't it match my slicer?

**Comment by FormerLurker** [comment] 2018-09-26 22:41
Sorry @geekdad63, I misread.  Leave it set to simplify then. If you aren't using all values, leave them blank.  Only a few are required.  Ignore the errors and warnings.  They only matter if you use 'feature detection' (layer change high quality snapshot profile).  It seems as though i
Need to figure out how to properly word the warnings.  Any advice would be greatly appreciated.

**Comment by JMCG1981** [comment] 2018-10-17 16:11
I am with the same problem I use the Simplify3D and I am not getting  the octolapse to work. I am suspicious that it is the Gcode Generated but I can not solve the problem.

**Comment by FormerLurker** [comment] 2018-10-17 16:32
@JMCG1981, can you provide me with more information?  First, check the version number you are using (look at the bottom right hand corner of the octolapse tab) and the version of Octoprint you are using (bottom left hand corner of the page, below the file browser).  If it is version 0.3.1 and your Octoprint version is 1.3.9, you will need to upgrade to a newer version of Octolapse.  Let me know if this is the case.

If you are using Octolapse 0.3.4.rc1.dev3, you won't need to upgrade, but you'll need to provide your logs and the gcode you are trying to print.  Ideally you could switch the 'debug' profile in Octolapse to 'Full Diagnostic - Test Mode', run a few layers (3 or 4) of your print, cancel, then download plugin_octolapse.log (from Octoprint settings (wrench)->Logs).  Also include your Octolapse settings (Octoprint Settings (wrench)->Octolapse->Download Settings).  Please include your printer model also.

Thanks!

**Comment by roguecode** [comment] 2019-01-27 11:04
I'm getting this on version 0.3.4 with OctoPrint 1.3.10.
It seems to be possible to bump it into working by starting a print then turning Octolapse off with the little power button. As you do that Octolapse tells you it'll turn off after the print, and it starts working.

**Comment by roguecode** [comment] 2019-01-27 13:47
Yeah, could just be a UI thing. I'll test it out later and let you know (just have to wait for this 10 print).
Would you mind clarifying what you mean about the printer stabilizing?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FormerLurker** [comment] 2019-01-27 13:52
@roguecode, Thanks!  What I mean by stabilization is that your printer moves to the correct spot for a snapshot.  It depends on your 'stabilization profile' in Octolapse exactly where this is.  If you set the stabilization to the back left or back right it will be hard to miss :)

FYI, I'm debugging the UI issue now.  If you confirm that the problem is related perhaps you'd be willing to try out the dev version when it is fixed?

**Comment by roguecode** [comment] 2019-01-28 09:16
Ah, ok, didn't know that was the term.

OK, confirmed that this is definitely a UI bug. Also, simply refreshing the page shows the right stuff.
Yup, of course would be happy to test. This is happening 100% of the time for me currently so will be easy to tell if it works.

**Comment by FormerLurker** [comment] 2019-01-28 23:37
Ok, great!  I've not gotten to the bottom of it yet.  I will hopefully have time this weekend though.  Pester me if you don't hear back :)

**Comment by FormerLurker** [comment] 2019-10-12 18:29
So I believe the UI issue (and many others) has been fixed in V0.4 (in testing now).  If anyone would like to try it out, please let me know.  I'm going to go ahead and close this issue, but can easily reopen it if anyone would like me to do so.  Or, just create a new issue and i'll take a look.  Thanks for posting!!!

**Closed by FormerLurker** 2019-10-12 18:29 UTC
Labels: Waiting for response, possible resolution
