### ISSUE TITLE
Error at Print Start - Slicer Settings are Missing

### ISSUE THREAD

**Issue by xcjacob30** [FormerLurker/Octolapse#551] opened 2020-06-18 13:21 UTC
#### Version of Octolapse
0.4.0

#### Version of OctoPrint
1.4.0

#### When you ran into the problem, did you have diagnostic logging enabled?
YES

#### What were you doing when the problem occurred

1. Configured Octolapse for Automatic Slicer settings with Cura V4.5 according to [this guide](https://github.com/FormerLurker/Octolapse/wiki/V0.4---Automatic-Slicer-Configuration#if-you-are-using-cura-follow-these-steps)
2. Received a popup error explaining that some settings were missing

#### What should have happened?
I expected the print to start

#### What happened instead?
Received a popup error explaining that some settings were missing

#### Operating System running OctoPrint and Octolapse
Octopi 0.17.0

#### Printer model & used firmware incl. version

cr-10 v2 with Marlin 2.0

#### Link to the gcode file you were printing when the problem occurred
https://gist.github.com/xcjacob30/1aa826b7dbdebd127790b830c6b7c774

#### Link to settings.json
https://gist.github.com/xcjacob30/1aa826b7dbdebd127790b830c6b7c774

#### Link to plugin_octolapse.log
https://gist.github.com/xcjacob30/1aa826b7dbdebd127790b830c6b7c774
#### Link to octoprint.log

NA
#### Link to contents of Javascript console in the browser

NA

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment] 2020-06-18 14:52
In the future please provide a better description of the problem than simply saying there was an error.  Knowing what error specifically, seeing a screen shot, or some other description is required, otherwise people looking at the issue would need to dig through the logs and make a guess about what the problem is.  Obviously that is unhelpful for anyone who might be having the same issue as you.

I was able to go through the plugin_octolapse.log file and see several errors.  Some look like they have been corrected (invalid ffmpeg path), but others do not.  If I'm right about the error you are having now, you should have seen an error toast that contained a help link (did you click the help button and see what it said??).

I looked at your gcode file, and it contains the settings script, but the settings tokens were NOT replaced by cura:

```
; Script based on an original created by tjjfvi (https://github.com/tjjfvi)
; An up-to-date version of the tjjfvi's original script can be found
; here:  https://csi.t6.fyi/
; Note - This script will only work in Cura V4.2 and above!
; --- Global Settings
; layer_height = {layer_height}
; smooth_spiralized_contours = {smooth_spiralized_contours}
; magic_mesh_surface_mode = {magic_mesh_surface_mode}
; machine_extruder_count = {machine_extruder_count}
; --- Single Extruder Settings
; speed_z_hop = {speed_z_hop}
; retraction_amount = {retraction_amount}
; retraction_hop = {retraction_hop}
; retraction_hop_enabled = {retraction_hop_enabled}
; retraction_enable = {retraction_enable}
; retraction_speed = {retraction_speed}
; retraction_retract_speed = {retraction_retract_speed}
; retraction_prime_speed = {retraction_prime_speed}
; speed_travel = {speed_travel
```

If you look at the last line above, you are missing a closing curly brace.  It should be :

```
; speed_travel = {speed_travel}
```

Replace that line and it should start working.

**Comment by xcjacob30** [comment] 2020-06-18 14:55
I'm very sorry for the trouble. I will take better care next time. Thank
you and have a great day.

**Comment by FormerLurker** [comment] 2020-06-18 14:56
@xcjacob30, it wasn't too much trouble, and I was glad to help.  please let me know if this fixes your problem.  I will adjust the title and issue description.

**Comment by FormerLurker** [comment] 2020-06-23 17:01
@xcjacob30, is this issue solved?

**Comment by xcjacob30** [comment] 2020-06-23 17:12
Yes sorry I forgot

**Comment by FormerLurker** [comment] 2020-06-23 17:16
No problem!  I'll go ahead and close this.  Enjoy the plugin!

**Closed by FormerLurker** 2020-06-23 17:16 UTC
