### ISSUE TITLE
Extrusion/Retraction issue?

### ISSUE THREAD

**Issue by spanzetta** [FormerLurker/Octolapse#570] opened 2020-07-21 12:56 UTC
Hello

first of all let me tell you a big thank and big congratulation for the great sw you developed...

Anyway.. after few usage I noticed a small problem caused by Octolapse... that maybe it's caused by some wrong settings (my fault)

If you look the attached screenshot (and the full video at the end of this report) you will notice a small imperfection caused by (not enough?) retraction so there is some extrusion in correspondence of the head position for octolapse pictures (in my case it was Centered/Smart-compatibility)

Is there something that can be done to improve the result by avoiding such small imperfection?

That issue doesn't happen if I disable Octolapse..

Thanks and regards

![Octolapse retraction issue](https://user-images.githubusercontent.com/49818743/88057139-edcb2080-cb61-11ea-84b9-f8d79797b100.png)

#### Version of Octolapse
Octolapse Version: 0.4.0

#### Version of OctoPrint
OctoPrint Version: 1.4.0

#### Operating System running OctoPrint and Octolapse
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

#### Printer model & used firmware incl. version
Printer Model: Ender 3 Pro
Printer Firmware Version: 1.1.6 (Original)

Pls check the full video at https://www.youtube.com/watch?v=HU7WurIzkGc

**Comment by Gordontgopher** [comment] 2020-07-23 09:55
Just to say I am seeing similar issues on my Prusa Mini running 4.1.0 with Octoprint / Octolapse running on a Pi 4B running RaspOS (raspbian) buster. Octolapse is configured for Centered/Smart-compatibility. First time I've used Octolapse, so it maybe a case of "PEBCAK" :) I will update if I discover anything significant.

**Comment by spanzetta** [comment] 2020-07-25 10:25
@Gordontgopher thanks for the confirmation 

Any comments/news form the author?

Thanks

**Comment by FormerLurker** [comment] 2020-07-29 16:22
Sorry about the delay all!  Been swamped here lately.

@Gordontgopher, I would try using fresh filament.  The prusa mini is known to have very few issues that would create the kinds of oozing artifacts seen in OPs image.  Direct drive greatly reduces the problem.  I do not see this when using my Mk2S UNLESS I am using old PLA or the temps are off, ESPECIALLY when stabilizing in the center.  However, if you are using a DSLR or have a large delay in your camera settings (more than 250MS), all bets are off :)

@spanzetta, I see this a lot for folks using printers similar to yours.  If you watch as Octolapse takes pictures, you will see a tiny bit of oozing filament get brushed off on the same spot over and over.  That's why they appear to grow up like that.  There are so many possible reasons for this that it's hard for me to go through them all.  Allow me to direct you to [this print quality guide](https://github.com/FormerLurker/Octolapse/wiki/V0.4---Troubleshooting-Print-Quality-Issues).  If you've already looked there please let me know.

**Comment by Gordontgopher** [comment] 2020-07-29 18:23
Thanks for the advice, the printer and filament (Prusament PLA) were about a week old, so I'd be surprised if this was the problem, but then again my experience only as old as the printer! I'm certainly not blaming Octolapse and realise the issue is probably the printer or the user :) I'll do some more experiments when I get a spare minute and follow up in the forum or discord if necessary.

**Comment by FormerLurker** [comment] 2020-07-29 19:05
Actually, feel free to blame Octolapse!  It can and does cause these problems, though I work hard to minimize it as much as possible.

Actually... Isn't the mini a bowden setup?  Oozing is generally more of a problem on those.  I don't have a mini, but I'm have seen plenty of videos without oozing, so I know it is possible.  If you can run Octolapse with no obvious quality issues you know you have a well tuned and well built machine!

**Comment by spanzetta** [comment] 2020-08-07 09:31
Dear
Nobody is blaming Octolapse..

We all should be (and I am) really grateful to you for your job (done for free/the community).

My intention was only to report you something that I noticed that maybe/eventually could have some solution (or improvement) on your code/sw side.. so the end scope is only to improve further your great sw.. 
Maybe a better Retraction management could solve/reduce the issue? Just a guess 

Thanks again for your great job

**Comment by FormerLurker** [comment] 2020-08-07 13:33
@spanzetta, thanks for your kind words!  Perhaps "blame" was the wrong word, but Octolapse definitely does cause these artifacts in some cases.  Just being honest.

Now, regarding retraction management, do you have any ideas how it can be improved?  I would be very interested in new ideas that would help things.

**Comment by spanzetta** [comment] 2020-08-07 13:40
Dear FromerLuker
Thanks for your reply..

My idea was to add the possibility to edit (into octolapse options)  the retraction command parameters that you add to the code before moving the head to the position to take the lapse picture (in my case it was "center").. 

If we could edit this value we could experiment different value to obtain better results..

I am assuming that before moving the head.. you add a retraction command.. isn't it?

Thanks a lot

**Comment by FormerLurker** [comment] 2020-08-07 14:35
I have thought about adding a retraction adjustment.  Currently it uses the slicer settings for retraction if you are using automatic slicer settings.  Perhaps an override would be a good feature.  Octolapse needs to know the slicer setting too though, in order to detect retraction for other quality reasons.

I have a few bugs to fix too, so I will look into that while I am working on those.

**Comment by spanzetta** [comment] 2020-08-07 15:06
_Octolapse needs to know the slicer setting too though, in order to detect retraction for other quality reasons._
you can start with supporting Cura (I use it and I assume it is the most used one)...
Thanks for considering it..

**Comment by FormerLurker** [comment] 2020-08-07 16:35
Are you currently using the automatic slicer settings detection with cura?

**Comment by spanzetta** [comment] 2020-08-07 16:53
Correct.. and I did follow your guide at https://github.com/FormerLurker/Octolapse/wiki/V0.4---Automatic-Slicer-Configuration#install-the-cura-settings-script

**Comment by ElCheekytico** [comment] 2020-08-27 16:26
I too have these zits/blobs at the point where the extruder moves away for the snapshot to be taken. I am using Cura with automatic configuration and have the gcode added per your guide referenced in the previous comment.

**Comment by FormerLurker** [comment] 2020-08-27 20:30
@ElCheekytico, have you looked at [this quality guide](https://github.com/FormerLurker/Octolapse/wiki/V0.4---Troubleshooting-Print-Quality-Issues)?  It may help.  I am working on allowing retraction adjustments, but it will take a while.  In general, most quality issues can be partially solved (perhaps not completely eliminated) by adjusting your slicer settings.

Also, if you post a pic of the issues you are seeing, I may be able to give you more specific advice.  The kinds of artifacts shown by OPs post are usually related to oozing.  Worse issues (giant blobs where the extruder left to take a snapshot) are usually due to configuration issues, most likely the G90/G91 influences extruder setting in the printer profile. 

Let me know

**Comment by ElCheekytico** [comment] 2020-08-31 18:39
> @ElCheekytico, have you looked at [this quality guide](https://github.com/FormerLurker/Octolapse/wiki/V0.4---Troubleshooting-Print-Quality-Issues)? It may help. I am working on allowing retraction adjustments, but it will take a while. In general, most quality issues can be partially solved (perhaps not completely eliminated) by adjusting your slicer settings.
> 
> Also, if you post a pic of the issues you are seeing, I may be able to give you more specific advice. The kinds of artifacts shown by OPs post are usually related to oozing. Worse issues (giant blobs where the extruder left to take a snapshot) are usually due to configuration issues, most likely the G90/G91 influences extruder setting in the printer profile.
> 
> Let me know

My apologies. I didn't realize what my flow rate was. I lowered that to a proper number and that mostly eliminated the zits/blobs.

**Comment by FormerLurker** [comment] 2020-08-31 19:22
That would make a difference.  Glad it is working, and thanks for the update!

**Comment by spanzetta** [comment] 2020-09-08 14:04
I am now testing with "**Smart - snap to print - smooth**" trigger (stabilization Disabled) and it seems to works perfectly!
No blobs/artefacts on printed object..
I think I will always use this method.. which works fine!
Thanks

**Comment by FormerLurker** [comment] 2020-09-09 20:02
@spanzetta, that is AWESOME!  I too love that trigger.  Depending on the model it can make a really cool timelapse, though it can also yield a pretty jerky timelapse in some cases.  If you are interested primarily in quality and speed, that is the one to use :)

**Comment by spanzetta** [comment] 2020-09-10 10:06
@FormerLurker there is only one very small issue.. the first picture is taken when printing the side line (in the middle).. added by Cura  before starting any print..
Any idea why it happens?
Thanks

**Comment by FormerLurker** [comment] 2020-09-10 15:28
Yes I know.  It's most likely because the priming line is on a different layer (height wise) than the actual printed part.  This is extremely common since priming is within the start gcode and is not adjusted on a per-print bases.  There are a few ways to deal with this:

1.  Adjust the priming line height to match the layer height (a pain, can cause squished priming, not recommended)
2.  Set the 'priming height' within your printer profile to exactly match the height of the priming line.  You can discover this height by reviewing your start gcode.
3.  The easy way - Use the new @Octolapse command to tell Octolapse to ignore your start gcode entirely by putting this at the top of the start gcode:

@OCTOLAPSE STOP-SNAPSHOTS

Then again at the bottom of your start gcode add this:

@OCTOLAPSE START-SNAPSHOTS

I would also recommend adding this to the very beginning of your end gcode:

@OCTOLAPSE STOP-SNAPSHOTS

That way your start and end gcode will never affect your timelapse!  Enjoy :)

**Comment by spanzetta** [comment] 2020-09-13 15:52
Thanks a lot!! 
I add the suggested code to start/end g-code .. will test it soon and will let you know
Regards

**Comment by spanzetta** [comment] 2020-09-14 09:20
I can confirm.. it now works perfectly
see attached

[Stringing_Test_20200914110730.zip](https://github.com/FormerLurker/Octolapse/files/5217424/Stringing_Test_20200914110730.zip)

**Comment by FormerLurker** [comment] 2020-09-17 16:29
Excellent!  Shall I close this issue?

Very glad things are working now :)

**Comment by spanzetta** [comment] 2020-09-18 11:47
Sure.. it can be closed

Thanks a lot.

**Closed** 2020-09-18 12:18 UTC
