### ISSUE TITLE
Synchronization failed error, no frames were captured

### ISSUE THREAD

**Issue by 4Z1ZV** [FormerLurker/Octolapse#244] opened 2018-09-19 20:38 UTC
Printer: CR10 Mini

Latest version of Octoprint and Octolaps, installed today.

Default Octolaps setting.

RPI 3 Model B.

No errors nor related messages during print.

Error pops up at the print end just before green message - Saved to SD Card..

No file saved.

**Comment by 4Z1ZV** [comment] 2018-09-19 21:35
[SD CARD CASES PLA.gcode.txt](https://github.com/FormerLurker/Octolapse/files/2398791/SD.CARD.CASES.PLA.gcode.txt)


Attached please find a sample file with my current start and end G-Code.

**Comment by 4Z1ZV** [comment] 2018-09-19 22:11
Many thanks for you ultra fast response.

I will test it on my next job.

Will take longer this time...  :-)

**Comment by 4Z1ZV** [comment] 2018-09-30 18:31
OK. The solution does the job.

:-).

Hoever it raised new issue - The current height is constantly reported as 0.2mm.

When I disabled the Octolaps, the report is OK.

**Comment by 4Z1ZV** [comment] 2018-09-30 18:33
Just to be more accurate, the reported height show the real value when thete is a layer change and the print head is licated a the shot position.

**Comment by FormerLurker** [comment] 2018-09-30 18:48
Are you talking about the [DisplayLayerProgress](https://plugins.octoprint.org/plugins/DisplayLayerProgress/) plugin?  If not, maybe you could send me a snapshot of what you're seeing?

**Comment by 4Z1ZV** [comment] 2018-09-30 19:08
====================
Zvi Segal
zvisegal@yahoo.com
Mobile: +972-546-666651
4Z1ZV
====================

Sorry for typos, sent from my mobile.... 
 
  On Sun, Sep 30, 2018 at 9:48 PM, FormerLurker<notifications@github.com> wrote:   
Are you talking about the DisplayLayerProgress plugin? If not, maybe you could send me a snapshot of what you're seeing?

**Comment by 4Z1ZV** [comment] 2018-10-01 10:41
Here is a copy of the printer state.

Once I enable the Octolaps,  Current Height remain unchanged except for layer change (when printer head goes to the defined position).


File: CR-10_Dial_Indicator_PETG.gcode 
User: zvika
Timelapse: On Z Change
Filament (Tool 0): 9.28m
Approx. Total Print Time: 1 hour
Print Time: 00:14:08
Print Time Left: 1 hour ●
Printed: 309.3KB / 1.9MB
Current Height: -0.20mm
Current Height: 0.20 / 30.52mm 
Layer: 10 / 108

**Comment by FormerLurker** [comment] 2018-10-01 17:32
@4Z1ZV, 

I don't have a 'Current Height' on my instance.  I still think that looks like the [DisplayLayerProgress](https://plugins.octoprint.org/plugins/DisplayLayerProgress/) plugin.  Can you verify that you have the DisplayLayerProgress plugin installed?  If so, you may want to post an issue on the DisplayLayerProgress plugin page [here](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/new).

Also, if you look in the Octolapse tab, open the current settings by clicking the link, and enable the position and position state info panels (sliders at the bottom) while a print and Octolapse is running, you should see the correct height/layer numbers.

Please let me know one way or another.

**Comment by 4Z1ZV** [comment] 2018-10-01 20:08
I enabled the position and position state.
It does open a window and show the correct height.

However the reported height on the main tub is still incorrect.

When I disable the Octolaps, event during print, on the next layer it shows the correct value.

**Comment by FormerLurker** [comment] 2018-10-01 20:32
@4Z1ZV, sorry to ask again, but you didn't answer my question about the [DisplayLayerProgress plugin](https://plugins.octoprint.org/plugins/DisplayLayerProgress/).  Did you install this plugin?  I'm just trying to figure out what is going on, and this will help.

**Comment by 4Z1ZV** [comment] 2018-10-01 20:54
The DisplayLayerProgress was installed.

I also tried to disable it. SAME ISSUE.

When I disable the Octolaps - The Height value is OK.

When I disable the Octolaps - It shows the following:

On layer change it momentary shows the real height of the head.

Than it shows the relative value - related to the last lap position.

**Comment by FormerLurker** [comment] 2018-10-01 21:05
OK, thanks!  Now try to disable the 'DisplayLayerProgress' plugin, then REBOOT Octoprint, then try running a print (rebooting is probably required to completely disable the plugin).  I'm pretty sure the height/layer display will vanish from OctoPrint.  If that's the case (and I'm pretty sure it is) then the problem is with the DisplayLayerProgress plugin and not Octolapse.

My guess would be the DisplayLayerProgress plugin isn't able to correctly account for relative Z movements (G91), and you should probably post this issue to the DisplayLayerProgress plugin home page here:  https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/new

**Comment by FormerLurker** [comment] 2018-10-02 19:07
Thanks for going back and forth with me, I know debugging can be frustrating.  

So here is what you say you are seeing:
```
File: CR-10_Dial_Indicator_PETG.gcode
User: zvika
Timelapse: On Z Change
Filament (Tool 0): 9.28m
Approx. Total Print Time: 1 hour
Print Time: 00:14:08
Print Time Left: 1 hour ●
Printed: 309.3KB / 1.9MB
Current Height: -0.20mm
Current Height: 0.20 / 30.52mm
Layer: 10 / 108
```

Here is what I'm seeing:

![capture](https://user-images.githubusercontent.com/33363128/46370792-3c858e80-c64c-11e8-9c1a-8fecd8cdc8dd.PNG)

I don't even see the 'Current Height' or 'Layer' information on my printer state panel, so I'm really confused how/why it's there!  Any thoughts?

**Comment by 4Z1ZV** [comment] 2018-10-02 19:18
[
![screenshot_20181002-221433](https://user-images.githubusercontent.com/24498878/46371402-edae1800-c690-11e8-8a43-5a03e79d3b71.jpg)
](url)

This is my screen at Offline state.

**Comment by 4Z1ZV** [comment] 2018-10-02 19:45
It is time to update to latest release :-)

**Comment by Shadowen** [comment] 2018-10-13 19:13
Not sure if this was mentioned, but @4Z1ZV 's screenshot is obviously taken on mobile... with the TouchUI plugin: https://plugins.octoprint.org/plugins/touchui/. I stopped using that plugin a while ago because it wasn't working well for me, but your experience may vary.

**Comment by FormerLurker** [comment] 2019-10-12 18:28
So, this is now a pretty old feature, and it's very possible that if this was a bug it's been solved in one of the many updates over the last year.  I'm going to close this down, but if you would like me to reopen, please let me know, or just post a new issue.  Thanks for your post!!!

**Closed by FormerLurker** 2019-10-12 18:28 UTC
Labels: possible resolution
