### ISSUE TITLE
Ultimaker 2 - Octolapse not working (Stabilization ERrOR + G21 ERROR)

### ISSUE THREAD

**Issue by TomyVertigo** [FormerLurker/Octolapse#624] opened 2020-11-11 16:35 UTC
#### OctoPrint Version 1.4.2
[plugin_octolapse.log](https://github.com/FormerLurker/Octolapse/files/5525276/plugin_octolapse.log)]

I have Ultimaker 2 and slicing with Cura 4.8.0

When I try to make octolapse I keep getting Stabilization Error and G21 error as mentioned in some other posts, but did not get solution how to fix it anywhere. :(

G21 ERROR:
The printer profile requires an explicit G21 command before any position altering/setting commands, including any home commands. Stopping timelapse, but continuing the print.

Thank you.

**Comment by FormerLurker** [comment] 2020-11-11 18:06
I need your settings json and other info that was in the issue template.  Are you running on a raspberry pi or some other OS?  If so, which one and which version.  Are you using OctoPi?  If so, which version?

However, it does look like the same error I'm seeing in other places and is likely caused by some bad compilation.  Try the classic layer trigger and see if that works.

**Comment by FormerLurker** [comment] 2020-11-11 18:09
See Issue #566

**Comment by TomyVertigo** [comment] 2020-11-11 18:40
Here you go: 
[settings.zip](https://github.com/FormerLurker/Octolapse/files/5526037/settings.zip)

I am running RaspBerry Pi4 8GB. Yes, I am using OctoPi v0.18.

Layer triggering not working. The only thing that is working (with error, tough) is:
Stabilization: Disabled
Trigger: SMART - Snap to print

Whan can I do?

**Comment by FormerLurker** [comment] 2020-11-11 18:55
Are you running python 3 or python 2?

You could try to update your distro, then uninstall and re-install Octolapse (you don't have to delete your settings).  I suspect this issue is compiler related.

[Here is a guide for updating installed packages.](https://www.raspberrypi.org/documentation/raspbian/updating.md).  Just run the first two apt updates: ```sudo apt update``` and ```sudo apt full-upgrade```.

FYI, this appears to be happening only for some ppl using the PI4, for only some flavors of linux, and on some instances running on MacOs.  I've got a pi4 on order, so hopefully I will finally be able to replicate this.

I'll leave this issue open until I hear if the above fixed things for you, then you can head over to Issue #566 for updates.  Sound good?

**Comment by TomyVertigo** [comment] 2020-11-11 19:43
FormerLurker, I did as you suggested and it looks like the G21 error is gone, but still facing 
**Stabilization Error**
_An unexpected error was encountered while running the timelapse snapshot procedure._

Octolapse is not working.

**Comment by TomyVertigo** [comment] 2020-11-11 19:46
Well G21 Error is not gone all the way: 
**Octolapse Timelapse Stopped**
_The printer profile requires an explicit G21 command before any position altering/setting commands, including any home commands. Stopping timelapse, but continuing the print._

Octolapse settings:
Stabilization: Centered
Trigger: Classic - GCODE

**Comment by FormerLurker** [comment] 2020-11-11 20:53
Yeah, so I think you're still hitting the same issue, which is a problem communicating to the compiled python extension.  Maybe I can send an SO file you can drop into the installation folder that I know works.  I can grab one off my pi.  Will send it soon.

**Comment by FormerLurker** [comment] 2020-11-11 20:55
Hey, are you using python 2 or 3?  It makes a difference, because I need to link to a different library.

**Comment by TomyVertigo** [comment] 2020-11-11 21:38
That would be great. 

I am running python v2.7.16.

**Comment by FormerLurker** [comment] 2020-11-11 21:49
[GcodePositionProcessor.zip](https://github.com/FormerLurker/Octolapse/files/5526898/GcodePositionProcessor.zip)

put it here:  home\pi\oprint\lib\python2.7\site-packages\GcodePositionProcessor.so

Let me know if that fixes it or if your pi catches fire and explodes :)

**Comment by FormerLurker** [comment] 2020-11-11 21:51
OH, you will need to completely reboot your pi for that to take affect.

**Comment by TomyVertigo** [comment] 2020-11-11 21:54
So... I do completely fresh install of the OctoPi?

**Comment by FormerLurker** [comment] 2020-11-11 21:57
No, you just copy that file to the path (i recommend sftp, like filezilla), reboot (not just restartin octoprint) and try again

**Comment by FormerLurker** [comment] 2020-11-11 21:58
If it works, at least it will narrow down what is causing this..  if the same issue happens... Not sure

**Comment by TomyVertigo** [comment] 2020-11-11 21:58
OK. Will do that and let you know. 

I really hope this fixes all. :)

**Comment by FormerLurker** [comment] 2020-11-11 22:00
You and me both...  Been working on my new plugin, arc welder, and have been swamped with new issues since the pi 4 and hd picam came out.  Would be happy to figure out what is going on

**Comment by TomyVertigo** [comment] 2020-11-11 22:22
I have only home\pi\oprint\lib\python3.7\site-packages\ and there is none file named GcodePositionProcessor.so
Is that OK? Should I put it here?

**Comment by FormerLurker** [comment] 2020-11-11 22:43
I thought you said you were running python 2???  I'm really confused.  you shouldn't even have a 3.7 directory!

Can you search for GcodePositionProcessor.so and tell me where you find it?  FYI, something must be up with the permissions because I've not been able to find my copy via the find / command.....  As if things aren't already complicated enough :)

**Comment by FormerLurker** [comment] 2020-11-11 22:47
Ok..  find is ..  odd.  Try running this from the home folder:

find . -name GcodePositionProcessor.so -type f


That should tell you where the current file is.  Then put the file I attached in there and overwrite it.

**Comment by TomyVertigo** [comment] 2020-11-12 05:15
So... there was only file GcodePositionProcessor.cpython-37m-aarch64-linux-gnu so I replace this file. 
But,,, when I reboot my OctoPrint there was no Octolapse installed anymore...

**Comment by TomyVertigo** [comment] 2020-11-12 05:44
And now I am getting an Internal server error in Cura.

**Comment by FormerLurker** [comment] 2020-11-12 05:46
Yeah, that shouldn't have been overwritten i don't think.  Not sure what the cura error is.

**Comment by FormerLurker** [comment] 2020-11-12 05:47
Will get back to yot tomorrow after I sleep and have time to think.

**Comment by TomyVertigo** [comment] 2020-11-12 08:20
No improvement in Octolapse, still facing the same errors.
[plugin_octolapse (1).log](https://github.com/FormerLurker/Octolapse/files/5529126/plugin_octolapse.1.log)

**Comment by FormerLurker** [comment] 2020-11-12 13:41
What steps did you perform since last time??

**Comment by TomyVertigo** [comment] 2020-11-12 14:03
_there was only file GcodePositionProcessor.cpython-37m-aarch64-linux-gnu so I replace this file._ With the file you send me. I also copied an unchanged file into this folder. 

Any other suggestions?

**Comment by TomyVertigo** [comment] 2020-11-12 15:34
@FormerLurker do you think that could be related to 64bit structure of (RaspBerry Pi4) 8GB version?

**Comment by FormerLurker** [comment] 2020-11-12 16:10
Good question.  It is entirely possible.  Maybe try a 32 bit version as a test if you have a spare sd?

**Comment by TomyVertigo** [comment] 2020-11-12 16:11
I also ordered 4GB version of RaspBerry Pi4 and will be testing it for the weekend. I want to come to the ground to this problem.

**Comment by FormerLurker** [comment] 2020-11-17 18:12
@TomyVertigo, can you try installing from the plugin manager using this link in the *From Url...* box:  ```https://github.com/FormerLurker/Octolapse/archive/88aa71f0fbac306b0d9acf19dff7388a30b29b64.zip```

See if that fixes it.

**Comment by TomyVertigo** [comment] 2020-11-18 12:04
@FormerLurker this feels like a great improvement, (at least) for now G21 is gone, but full functionality is still not there. Just tried orbit mode and it is not working correctly.

**Comment by FormerLurker** [comment] 2020-11-18 13:29
I need more info to help you with that.  How exactly is it not working?

**Comment by TomyVertigo** [comment] 2020-11-18 13:34
Here you go. Some files regarding the latest Octolapse.
[OctoLapse.zip](https://github.com/FormerLurker/Octolapse/files/5560312/OctoLapse.zip)

Octolapse settings:
![image](https://user-images.githubusercontent.com/63294196/99536842-2f9e9300-29ab-11eb-9b4a-d6fa9c113d4c.png)

**Comment by FormerLurker** [comment] 2020-11-18 13:43
Are you familiar with what the 'snap to print' trigger actually does?  It doesn't allow the printhead to move off of the part or away from the tool paths at all, so it creates a time lapse that is as close as possible.  Try using a fixed position stabilization for that, like back left or something.  If you want a true orbit, try using ng the smart layer trigger.

**Comment by FormerLurker** [comment] 2020-11-18 13:48
I should have mentioned this sooner, but check in the trigger profile setting for the little blue question marks.  I have added a lot of info that should explain what each trigger does and how the settings affect them.  If i misunderstood your issue, please let me know

**Comment by TomyVertigo** [comment] 2020-11-18 13:58
> Are you familiar with what the 'snap to print' trigger actually does? It doesn't allow the printhead to move off of the part or away from the tool paths at all, so it creates a time lapse that is as close as possible. Try using a fixed position stabilization for that, like back left or something. If you want a true orbit, try using ng the smart layer trigger.

OK. I left it from before when nothing else didn't work. I will try now and let you know. 

I still get stabilization errors tough.

**Comment by FormerLurker** [comment] 2020-11-18 14:58
If the stabilization errors keep occurring, I recommend creating a new issue.  I recommend running a very small print (calibration cube or something similar) and logging with the 'debug' profile until the error occurs, then you can stop the print and upload the log.  [Here are some instructions](https://github.com/FormerLurker/Octolapse/wiki/V0.4---Reporting-An-Issue#creating-an-octolapse-log-file) for accomplishing this that should yield a clean log file.

**Comment by TomyVertigo** [comment] 2020-11-18 17:17
Run a few test prints now and no error accourd. Great job @FormerLurker 💯

**Comment by FormerLurker** [comment] 2020-11-18 17:36
Awesome!  Going to close this.  If you have any other issues, please let me know!

**Closed by FormerLurker** 2020-11-18 17:36 UTC
Labels: duplicate, possible resolution
